import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import styles from '../styles/Home.module.scss';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Test App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>Hello in our shop</h1>
            <Link href="/shop">
                <a className="bordered-link">Check what you can buy</a>
            </Link>
        </div>
    );
}
